import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const head='10000000-0000-4000-8000-000000000001',teacher='10000000-0000-4000-8000-000000000002',other='10000000-0000-4000-8000-000000000003',unconfirmed='10000000-0000-4000-8000-000000000004';
test('Account approval is enforced by PostgreSQL, including direct API bypass attempts',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,storage to authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text,metadata jsonb);
 alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to authenticated;`);
 await db.exec(await readFile('supabase/setup.sql','utf8'));
 await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${head}','head@school.example',now());update profiles set role='head',is_owner=true where id='${head}';`);
 const migration=await readFile('supabase/account-approval.sql','utf8');await db.exec(migration);
 await db.exec(`insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values('${teacher}','teacher@school.example',now(),'\{"role":"head","approval_status":"approved","full_name":"Google Teacher"\}'),('${other}','other@school.example',now(),'{}'),('${unconfirmed}','unconfirmed@school.example',null,'{}');`);
 const as=async uid=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role authenticated')};
 await as(teacher);let state=(await db.query('select get_state()')).rows[0].get_state;
 assert.equal(state.user.role,'teacher');assert.equal(state.user.approval_status,'pending');assert.equal(state.user.name,'Google Teacher');assert.deepEqual(state.modules,[]);assert.deepEqual(state.teachers,[]);
 await assert.rejects(db.query("update profiles set approval_status='approved' where id=$1",[teacher]),/permission denied/);
 await assert.rejects(db.query("select decide_account($1,'approved','')",[teacher]),/Only an approved Head Teacher/);
 await assert.rejects(db.query("select change_role($1,'head')",[teacher]),/permission denied/);
 await assert.rejects(db.query("insert into notes(title,body) values('Bypass','Not allowed')"),/row-level security/);
 await assert.rejects(db.query("insert into storage.objects(bucket_id,name,owner_id) values('sikap-modules',$1,$2)",[teacher+'/fake/v1.pdf',teacher]),/row-level security/);
 await assert.rejects(db.query("select submit_module(gen_random_uuid(),'{}','fake','x.pdf','application/pdf',10)"),/approval required/);
 await assert.rejects(db.query('select archive_module(gen_random_uuid(),true)'),/approval required/);
 await as(head);state=(await db.query('select get_state()')).rows[0].get_state;
 assert.equal(state.user.approval_status,'approved');assert.equal(state.teachers.length,4);
 await assert.rejects(db.query("select decide_account($1,'approved','')",[unconfirmed]),/confirm their email/);
 await assert.rejects(db.query("select decide_account($1,'head','')",[teacher]),/Invalid account decision/);
 await db.query("select decide_account($1,'approved','Welcome to school')",[teacher]);
 await assert.rejects(db.query("select decide_account($1,'rejected','Stale click')",[teacher]),/not awaiting approval/);
 await db.query("select decide_account($1,'rejected','Contact the school')",[other]);
 await as(teacher);state=(await db.query('select get_state()')).rows[0].get_state;assert.equal(state.user.role,'teacher');assert.equal(state.user.approval_status,'approved');assert.equal(state.user.decided_by,head);
 await db.query("insert into notes(title,body) values('Allowed','Approved teacher')");
 await as(other);state=(await db.query('select get_state()')).rows[0].get_state;assert.equal(state.user.approval_status,'rejected');assert.equal(state.user.approval_note,'Contact the school');assert.deepEqual(state.notes,[]);assert.equal((await db.query('select * from notes')).rows.length,0);
 await db.exec('reset role');await db.exec(migration);assert.equal((await db.query('select count(*)::int as n from account_reviews')).rows[0].n,2);assert.equal((await db.query('select approval_status from profiles where id=$1',[teacher])).rows[0].approval_status,'approved');
 await db.close();
});
