import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
const head='10000000-0000-4000-8000-000000000001',teacher='10000000-0000-4000-8000-000000000002',other='10000000-0000-4000-8000-000000000003',mid='20000000-0000-4000-8000-000000000001';
test('Real PostgreSQL: access isolation, revisions, approvals, owner roles and private immutable files',async()=>{
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,storage to authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text,metadata jsonb);
 alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to authenticated;`);
 await db.exec(await readFile('supabase/setup.sql','utf8'));
 await db.exec(`insert into auth.users(id,email,raw_user_meta_data) values('${head}','head@school.example','{"name":"Head Teacher","role":"head"}'),('${teacher}','teacher@school.example','{"name":"Teacher"}'),('${other}','other@school.example','{"name":"Other"}');`);
 assert.equal((await db.query('select role from profiles where id=$1',[head])).rows[0].role,'teacher');
 await db.exec(`update profiles set role='head',is_owner=true where id='${head}';`);
 const as=async uid=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role authenticated')};
 const pdf={key:teacher+'/'+mid+'/v1.pdf',name:'lesson.pdf',type:'application/pdf',size:40};
 await as(teacher);await db.query('insert into storage.objects(bucket_id,name,owner_id,metadata) values($1,$2,$3,$4)',['sikap-modules',pdf.key,teacher,{size:40,mimetype:pdf.type}]);
 await db.query('select submit_module($1,$2,$3,$4,$5,$6)',[mid,{title:'Fractions',subject:'Mathematics',grade:'Grade 5',term:'Quarter 1',year:'2026–2027'},pdf.key,pdf.name,pdf.type,40]);
 assert.equal((await db.query('select get_state()')).rows[0].get_state.modules.length,1);
 await assert.rejects(db.query("update profiles set role='head' where id=$1",[teacher]),/permission denied/);
 await assert.rejects(db.query("update modules set status='approved' where id=$1",[mid]),/permission denied/);
 await assert.rejects(db.query("select review_module($1,1,'approved','')",[mid]),/head teacher/);
 await as(other);assert.equal((await db.query('select * from modules')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(db.query('select module_details($1)',[mid]),/access denied/);
 await as(head);await assert.rejects(db.query("select review_module($1,1,'returned','')",[mid]),/feedback/);await assert.rejects(db.query("select review_module($1,1,'returned',null)",[mid]),/feedback/);await db.query("select review_module($1,1,'returned','Add a rubric')",[mid]);
 await as(teacher);const key2=teacher+'/'+mid+'/v2.pdf';await db.query('insert into storage.objects(bucket_id,name,owner_id,metadata) values($1,$2,$3,$4)',['sikap-modules',key2,teacher,{size:40,mimetype:pdf.type}]);
 await db.query('select revise_module($1,2,$2,$3,$4,40,$5)',[mid,key2,'revised.pdf',pdf.type,'Added assessment rubric']);
 assert.equal((await db.query('select * from versions')).rows.length,2);
 await as(head);await assert.rejects(db.query("select review_module($1,1,'approved','')",[mid]),/changed/);await db.query("select review_module($1,3,'approved','Looks good')",[mid]);
 await as(teacher);const detail=(await db.query('select module_details($1)',[mid])).rows[0].module_details;assert.equal(detail.module.final_version,2);assert.equal(detail.module.approver,head);assert.equal(detail.versions.length,2);assert.equal(detail.comments.length,2);
 await assert.rejects(db.query('select revise_module($1,4,$2,$3,$4,40,$5)',[mid,key2,'revised.pdf',pdf.type,'Overwrite']),/locked/);
 assert.equal((await db.query('update storage.objects set name=$1 where name=$2 returning *',['overwritten.pdf',key2])).rows.length,0);
 assert.equal((await db.query('delete from storage.objects where name=$1 returning *',[key2])).rows.length,0);
 await db.query('insert into notes(title,body) values($1,$2)',['Private','Teacher notes']);await as(other);assert.equal((await db.query('select * from notes')).rows.length,0);await assert.rejects(db.query("select change_role($1,'head')",[other]),/Only the owner/);
 await as(head);await db.query("select change_role($1,'head')",[other]);await db.exec('reset role');assert.equal((await db.query('select role from profiles where id=$1',[other])).rows[0].role,'head');await db.close();
});
